# ********RoostGPT********

# Test generated by RoostGPT for test k-api-dbrx-may23 using AI Type DBRX and AI Model meta-llama-3-70b-instruct-041824
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=56bfcadf64
# 
# 

# ********RoostGPT********
Feature: Get Laureate by ID
  As a user
  I want to get a laureate by ID
  So that I can access laureate information

  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

  Scenario Outline: Get Laureate by ID with valid ID
    Given path '/2.1/laureate/{laureateID}'
    And param laureateID = <laureateID>
    When method GET
    Then status <statusCode>
    And match response == """
      {
        code: <code>,
        message: <message>
      }
    """
    And match responseHeaders == <headers>

    Examples:
      | laureateID | statusCode | code | message                    | headers |
      |          1 |        200 |      |                            |         |
      |          2 |        404 |      | Laureate not found         |         |
      |          0 |        400 |      | Invalid request parameters |         |
      |         -1 |        422 |      | Unprocessable entity       |         |

  Scenario: Get Laureate by ID with invalid ID
    Given path '/2.1/laureate/abc'
    When method GET
    Then status 400
    And match response == """
      {
        code: 'Bad Request',
        message: 'Invalid request parameters'
      }
    """
    And match responseHeaders == 'No response headers'

  Scenario: Get Laureate by ID with missing ID
    Given path '/2.1/laureate/'
    When method GET
    Then status 404
    And match response == """
      {
        code: 'Not Found',
        message: 'Laureate not found'
      }
    """
    And match responseHeaders == 'No response headers'
