# ********RoostGPT********

# Test generated by RoostGPT for test k-api-dbrx-may23 using AI Type DBRX and AI Model meta-llama-3-70b-instruct-041824
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API
  As a user
  I want to obtain information about a specific Nobel Prize
  So that I can access the details of the award

  Scenario Outline: Get Nobel Prize by category and year
    Given url urlBase + '/2.1/nobelPrize/' + <category> + '/' + <year>
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    When method GET
    Then status <statusCode>
    And match response ==
      """
      <responseBody>
      """

    Examples:
      | read('nobelPrize_category_year_get.csv') |

  Scenario: Get Nobel Prize with invalid category
    Given url urlBase + '/2.1/nobelPrize/invalid/1990'
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    When method GET
    Then status 400
    And match response ==
      """
      {
        "code": "404",
        "message": "There is not Laureate born that date"
      }
      """

  Scenario: Get Nobel Prize with invalid year
    Given url urlBase + '/2.1/nobelPrize/physics/1800'
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    When method GET
    Then status 400
    And match response ==
      """
      {
        "code": "404",
        "message": "There is not Laureate born that date"
      }
      """
