# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-aviation using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-7-sonnet-20250219-v1:0
# 
# Test file generated for /api/data/taf_get for http method type GET 
# RoostTestHash=eaca34b3de
# 
# 

# ********RoostGPT********
import json
import os
import pytest
from jsonschema import validate
import logging

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def load_test_data():
    """Load test data from JSON file."""
    current_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(current_dir, "api_data_taf.json")
    
    try:
        with open(json_path, 'r') as file:
            data = json.load(file)
            logger.info(f"Successfully loaded test data with {len(data)} test cases")
            return data
    except Exception as e:
        logger.error(f"Failed to load test data: {str(e)}")
        pytest.fail(f"Failed to load test data: {str(e)}")


def validate_taf_schema(response_data):
    """Validate the response against TAF schema."""
    if not isinstance(response_data, list):
        return False
    
    # If empty list is returned, it's valid but has no data
    if len(response_data) == 0:
        return True
    
    # Basic schema for TAF data
    taf_schema = {
        "type": "object",
        "properties": {
            "icaoId": {"type": "string"},
            "dbPopTime": {"type": "string"},
            "bulletinTime": {"type": "string"},
            "issueTime": {"type": "string"},
            "validTimeFrom": {"type": "integer"},
            "validTimeTo": {"type": "integer"},
            "rawTAF": {"type": "string"},
            "mostRecent": {"type": "integer"},
            "lat": {"type": "number"},
            "lon": {"type": "number"},
            "elev": {"type": "integer"},
            "name": {"type": "string"}
        }
    }
    
    # Check each item in the list against the schema
    for item in response_data:
        try:
            validate(instance=item, schema=taf_schema)
        except Exception:
            return False
    
    return True


@pytest.mark.parametrize('test_case', load_test_data())
def test_get_taf_data(api_client, config, test_case):
    """
    Test the TAF API endpoint with various parameters.
    
    This test verifies the TAF (Terminal Aerodrome Forecast) endpoint behavior 
    with different parameter combinations including:
    - Station IDs
    - Bounding box
    - Output format
    - METAR inclusion
    - Time and date parameters
    
    It validates both successful responses and error scenarios based on the
    test data provided.
    """
    # Extract parameters from the test case
    params = {
        'ids': test_case.get('ids'),
        'bbox': test_case.get('bbox'),
        'format': test_case.get('format'),
        'metar': test_case.get('metar'),
        'time': test_case.get('time'),
        'date': test_case.get('date')
    }
    
    # Remove empty parameters
    params = {k: v for k, v in params.items() if v is not None and v != ""}
    
    # Log test scenario
    logger.info(f"Testing scenario: {test_case.get('scenario')}")
    logger.info(f"Parameters: {params}")
    
    # Make the API request
    endpoint = "api/data/taf"
    response = api_client.get(endpoint, params=params)
    
    # Validate the response status code
    expected_status = test_case.get('statusCode')
    assert response.status_code == expected_status, (
        f"Expected status code {expected_status}, got {response.status_code}. "
        f"Response: {response.text}"
    )
    
    # For successful responses, validate the structure and content
    if expected_status == 200:
        # If format is specified and not json, we can't validate the JSON schema
        if test_case.get('format') and test_case.get('format').lower() != 'json':
            # Just check that we have a response
            assert response.text, "Empty response received for successful request"
        else:
            try:
                response_json = response.json()
                
                # Validate that it's an array
                assert isinstance(response_json, list), "Response should be an array"
                
                # Validate schema if there are items
                if response_json:
                    assert validate_taf_schema(response_json), "Response does not match expected TAF schema"
                    
                    # Validate specific fields if they exist
                    for item in response_json:
                        if 'icaoId' in item:
                            assert isinstance(item['icaoId'], str), "icaoId should be a string"
                        if 'fcsts' in item and item['fcsts']:
                            for fcst in item['fcsts']:
                                assert 'timeFrom' in fcst, "timeFrom should be present in forecast"
                                assert 'timeTo' in fcst, "timeTo should be present in forecast"
                                
            except json.JSONDecodeError:
                # If format is not specified, the default should be JSON
                if not test_case.get('format'):
                    pytest.fail("Response is not valid JSON")
    
    # For error responses, validate the error structure
    elif expected_status == 400:
        try:
            error_response = response.json()
            assert 'status' in error_response, "Error response should contain 'status' field"
            assert 'error' in error_response, "Error response should contain 'error' field"
        except json.JSONDecodeError:
            pytest.fail("Error response is not valid JSON")
    
    logger.info(f"Test completed for scenario: {test_case.get('scenario')}")


if __name__ == "__main__":
    # This allows the test to be run directly if needed
    pytest.main(["-xvs", __file__])
