# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-aviation using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-7-sonnet-20250219-v1:0
# 
# Test file generated for /api/data/taf_get for http method type GET 
# RoostTestHash=eaca34b3de
# 
# 

# ********RoostGPT********
import pytest
import os
from datetime import datetime, timedelta
import json
from urllib.parse import urlencode

@pytest.fixture
def taf_endpoint():
    return "api/data/taf"

@pytest.fixture
def sample_taf_ids():
    return ["KJFK", "KLAX", "KORD", "KATL", "KSEA"]

@pytest.fixture
def valid_bbox():
    return "-122.4,37.6,-122.2,37.8"  # San Francisco area

@pytest.fixture
def valid_time():
    current_time = datetime.utcnow()
    formatted_time = current_time.strftime("%Y-%m-%dT%H:%M:%SZ")
    return formatted_time

@pytest.fixture
def valid_date():
    current_date = datetime.utcnow()
    formatted_date = current_date.strftime("%Y-%m-%d")
    return formatted_date

@pytest.fixture
def expected_taf_keys():
    return [
        "icaoId", "dbPopTime", "bulletinTime", "issueTime", 
        "validTimeFrom", "validTimeTo", "rawTAF", "mostRecent", 
        "remarks", "lat", "lon", "elev", "prior", "name", "fcsts"
    ]

@pytest.fixture
def expected_fcst_keys():
    return [
        "timeFrom", "timeTo", "timeBec", "fcstChange", "probability",
        "wdir", "wspd", "wgst", "wshearHgt", "wshearDir", "wshearSpd",
        "visib", "altim", "vertVis", "wxString", "notDecoded", 
        "clouds", "icgTurb", "temp"
    ]

class TestTafEndpoint:
    """Tests for the /api/data/taf endpoint."""

    def test_get_taf_by_single_id(self, api_client, taf_endpoint, sample_taf_ids, expected_taf_keys, schema_validator):
        """Test retrieving TAF data by a single station ID."""
        # Use first ID from sample list
        test_id = sample_taf_ids[0]
        params = {"ids": test_id}
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
        assert len(data) > 0
        
        # Validate the first TAF object
        taf = data[0]
        assert taf["icaoId"] == test_id
        for key in expected_taf_keys:
            assert key in taf
        
        # Validate schema
        assert schema_validator.validate_schema_TAFJSON(data)

    def test_get_taf_by_multiple_ids(self, api_client, taf_endpoint, sample_taf_ids):
        """Test retrieving TAF data by multiple station IDs."""
        # Use first three IDs from sample list
        test_ids = ",".join(sample_taf_ids[:3])
        params = {"ids": test_ids}
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
        
        # Check that we have TAFs for the requested stations
        received_ids = [taf["icaoId"] for taf in data]
        for test_id in test_ids.split(","):
            assert test_id in received_ids

    def test_get_taf_by_bbox(self, api_client, taf_endpoint, valid_bbox):
        """Test retrieving TAF data by bounding box."""
        params = {"bbox": valid_bbox}
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
        
        # Check if the returned stations are within the bbox
        if data:
            min_lon, min_lat, max_lon, max_lat = map(float, valid_bbox.split(','))
            for taf in data:
                assert min_lon <= taf["lon"] <= max_lon
                assert min_lat <= taf["lat"] <= max_lat

    def test_get_taf_with_format_json(self, api_client, taf_endpoint, sample_taf_ids):
        """Test retrieving TAF data with JSON format."""
        test_id = sample_taf_ids[0]
        params = {"ids": test_id, "format": "json"}
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
        assert len(data) > 0

    def test_get_taf_with_format_xml(self, api_client, taf_endpoint, sample_taf_ids):
        """Test retrieving TAF data with XML format."""
        test_id = sample_taf_ids[0]
        params = {"ids": test_id, "format": "xml"}
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 200
        assert "xml" in response.headers.get('Content-Type', '')
        
        # XML response should contain the ID we requested
        assert test_id in response.text

    def test_get_taf_with_format_geojson(self, api_client, taf_endpoint, sample_taf_ids):
        """Test retrieving TAF data with GeoJSON format."""
        test_id = sample_taf_ids[0]
        params = {"ids": test_id, "format": "geojson"}
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 200
        data = response.json()
        
        # Verify GeoJSON structure
        assert "type" in data
        assert data["type"] == "FeatureCollection"
        assert "features" in data
        assert isinstance(data["features"], list)

    def test_get_taf_with_metar_true(self, api_client, taf_endpoint, sample_taf_ids):
        """Test retrieving TAF data with METAR inclusion."""
        test_id = sample_taf_ids[0]
        params = {"ids": test_id, "metar": "true"}
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
        assert len(data) > 0
        
        # Check if metar field is included in the response
        # The field name might vary based on the actual API response structure
        # This is a reasonable guess but may need adjustment
        if "metar" in data[0]:
            assert data[0]["metar"] is not None

    def test_get_taf_with_time_parameter(self, api_client, taf_endpoint, sample_taf_ids, valid_time):
        """Test retrieving TAF data with specific time parameter."""
        test_id = sample_taf_ids[0]
        params = {"ids": test_id, "time": valid_time}
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)

    def test_get_taf_with_date_parameter(self, api_client, taf_endpoint, sample_taf_ids, valid_date):
        """Test retrieving TAF data with specific date parameter."""
        test_id = sample_taf_ids[0]
        params = {"ids": test_id, "date": valid_date}
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)

    def test_get_taf_no_parameters(self, api_client, taf_endpoint):
        """Test retrieving TAF data with no parameters - should return an error."""
        response = api_client.get(taf_endpoint)
        
        # Expect a 400 Bad Request since parameters are required
        assert response.status_code == 400
        
        # Validate error response structure
        error = response.json()
        assert "status" in error
        assert "error" in error

    def test_get_taf_invalid_ids(self, api_client, taf_endpoint):
        """Test retrieving TAF data with invalid station IDs."""
        invalid_id = "INVALID123"
        params = {"ids": invalid_id}
        
        response = api_client.get(taf_endpoint, params=params)
        
        # May return 200 with empty array or 400 with error
        if response.status_code == 200:
            data = response.json()
            assert isinstance(data, list)
            assert len(data) == 0
        else:
            assert response.status_code == 400
            error = response.json()
            assert "status" in error
            assert "error" in error

    def test_get_taf_invalid_bbox(self, api_client, taf_endpoint):
        """Test retrieving TAF data with invalid bounding box."""
        invalid_bbox = "200,100,-200,-100"  # Invalid coordinates
        params = {"bbox": invalid_bbox}
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 400
        error = response.json()
        assert "status" in error
        assert "error" in error

    def test_get_taf_invalid_format(self, api_client, taf_endpoint, sample_taf_ids):
        """Test retrieving TAF data with invalid format."""
        test_id = sample_taf_ids[0]
        params = {"ids": test_id, "format": "invalid_format"}
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 400
        error = response.json()
        assert "status" in error
        assert "error" in error

    def test_get_taf_fcst_structure(self, api_client, taf_endpoint, sample_taf_ids, expected_fcst_keys):
        """Test the structure of forecast objects within TAF data."""
        test_id = sample_taf_ids[0]
        params = {"ids": test_id}
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
        assert len(data) > 0
        
        # Check if there are forecasts and validate their structure
        if "fcsts" in data[0] and data[0]["fcsts"]:
            fcst = data[0]["fcsts"][0]
            for key in expected_fcst_keys:
                assert key in fcst
                
            # Check cloud structure if present
            if fcst["clouds"]:
                cloud = fcst["clouds"][0]
                assert "cover" in cloud
                assert "base" in cloud

    def test_get_taf_with_combined_parameters(self, api_client, taf_endpoint, sample_taf_ids, valid_date):
        """Test retrieving TAF data with a combination of parameters."""
        test_id = sample_taf_ids[0]
        params = {
            "ids": test_id, 
            "date": valid_date,
            "format": "json",
            "metar": "true"
        }
        
        response = api_client.get(taf_endpoint, params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)

    def test_get_taf_query_limit(self, api_client, taf_endpoint):
        """Test the query limit by requesting a large number of IDs."""
        # Create a long list of IDs - may exceed API limits
        many_ids = ",".join([f"K{i:03d}" for i in range(100)])
        params = {"ids": many_ids}
        
        response = api_client.get(taf_endpoint, params=params)
        
        # If there's a limit and we exceeded it, expect 400
        # Otherwise, expect 200 with potentially fewer results than requested
        if response.status_code == 400:
            error = response.json()
            assert "status" in error
            assert "error" in error
        else:
            assert response.status_code == 200
            data = response.json()
            assert isinstance(data, list)

    def test_get_taf_response_time(self, api_client, taf_endpoint, sample_taf_ids):
        """Test the response time of the TAF endpoint."""
        import time
        
        test_id = sample_taf_ids[0]
        params = {"ids": test_id}
        
        start_time = time.time()
        response = api_client.get(taf_endpoint, params=params)
        end_time = time.time()
        
        response_time = end_time - start_time
        
        # Ensure response came back in a reasonable time (5 seconds is generous)
        assert response_time < 5.0
        assert response.status_code == 200
