# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-aviation using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-7-sonnet-20250219-v1:0
# 
# Test file generated for /api/data/taf_get for http method type GET 
# RoostTestHash=eaca34b3de
# 
# 

# ********RoostGPT********
import pytest
import json
import os
from pathlib import Path
from typing import Dict, Any, List
from validator import SwaggerSchemaValidator

# Load test data from JSON file
def load_test_data():
    """Load test data from JSON file."""
    current_dir = Path(__file__).parent
    data_path = os.path.join(current_dir, "api_data_taf.json")
    
    with open(data_path, 'r') as file:
        return json.load(file)

# Initialize the schema validator
@pytest.fixture(scope="session")
def schema_validator():
    """Initialize the schema validator with the OpenAPI spec."""
    return SwaggerSchemaValidator("https://aviationweather.gov/data/schema/openapi.yaml")

class TestTafAPI:
    """Test suite for TAF (Terminal Aerodrome Forecast) API."""
    
    ENDPOINT = "api/data/taf"
    
    @pytest.fixture(scope="class")
    def test_data(self):
        """Load test data for TAF API testing."""
        return load_test_data()
    
    def validate_response(self, status_code: int, response_data: Any, expected_status: int, scenario: str, schema_validator=None):
        """
        Validate API response based on expected status code and scenario.
        
        Args:
            status_code: Actual response status code
            response_data: Response data to validate
            expected_status: Expected status code
            scenario: Test scenario description
            schema_validator: Schema validator instance
        """
        assert status_code == expected_status, f"Expected status code {expected_status}, got {status_code} for scenario: {scenario}"
        
        # Validate response schema based on status code
        if status_code == 200 and response_data:
            # For successful responses, validate against the TAF response schema
            schema = {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "icaoId": {"type": "string"},
                        "dbPopTime": {"type": "string"},
                        "bulletinTime": {"type": "string"},
                        "issueTime": {"type": "string"},
                        "validTimeFrom": {"type": "integer"},
                        "validTimeTo": {"type": "integer"},
                        "rawTAF": {"type": "string"},
                        "mostRecent": {"type": "integer"},
                        "remarks": {"type": "string"},
                        "lat": {"type": "number"},
                        "lon": {"type": "number"},
                        "elev": {"type": "integer"},
                        "prior": {"type": "integer"},
                        "name": {"type": "string"},
                        "fcsts": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "timeFrom": {"type": "integer"},
                                    "timeTo": {"type": "integer"},
                                    "timeBec": {"type": "integer"},
                                    "fcstChange": {"type": "string"},
                                    "probability": {"type": "integer"},
                                    "wdir": {"type": "object"},
                                    "wspd": {"type": "integer"},
                                    "wgst": {"type": "integer"},
                                    "wshearHgt": {"type": "integer"},
                                    "wshearDir": {"type": "integer"},
                                    "wshearSpd": {"type": "integer"},
                                    "visib": {"type": "object"},
                                    "altim": {"type": "number"},
                                    "vertVis": {"type": "integer"},
                                    "wxString": {"type": "string"},
                                    "notDecoded": {"type": "string"},
                                    "clouds": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "cover": {"type": "string"},
                                                "base": {"type": "integer"},
                                                "top": {"type": "integer"}
                                            },
                                            "required": ["cover", "base"]
                                        }
                                    },
                                    "icgTurb": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "var": {"type": "string"},
                                                "intensity": {"type": "integer"},
                                                "minAlt": {"type": "integer"},
                                                "maxAlt": {"type": "integer"}
                                            },
                                            "required": ["var", "intensity", "minAlt", "maxAlt"]
                                        }
                                    },
                                    "temp": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "validTime": {"type": "integer"},
                                                "sfcTemp": {"type": "integer"},
                                                "maxOrMin": {"type": "string"}
                                            },
                                            "required": ["validTime", "sfcTemp", "maxOrMin"]
                                        }
                                    }
                                },
                                "required": [
                                    "timeFrom", "timeTo", "timeBec", "fcstChange", "probability",
                                    "wdir", "wspd", "wgst", "wshearHgt", "wshearDir", "wshearSpd", "visib",
                                    "altim", "vertVis", "wxString", "notDecoded", "clouds", "icgTurb", "temp"
                                ]
                            }
                        }
                    }
                }
            }
            
            if schema_validator:
                schema_validator.validate_with_schema(response_data, schema)
        elif status_code == 400 and response_data:
            # For error responses, validate against error schema
            error_schema = {
                "type": "object",
                "properties": {
                    "status": {"type": "string"},
                    "error": {"type": "string"}
                },
                "required": ["status", "error"]
            }
            
            if schema_validator:
                schema_validator.validate_with_schema(response_data, error_schema)
    
    @pytest.mark.parametrize("test_case_index", range(7))  # 7 test cases in the JSON file
    def test_taf_api(self, test_case_index, test_data, api_client, schema_validator):
        """
        Test the TAF API with various input combinations from test data file.
        
        Args:
            test_case_index: Index of the test case in the test data array
            test_data: Test data fixture
            api_client: API client fixture
            schema_validator: Schema validator fixture
        """
        # Get the test case data
        test_case = test_data[test_case_index]
        
        # Extract test parameters
        query_params = {
            "ids": test_case.get("ids"),
            "bbox": test_case.get("bbox"),
            "format": test_case.get("format"),
            "metar": test_case.get("metar"),
            "time": test_case.get("time"),
            "date": test_case.get("date")
        }
        
        # Clean up empty parameters
        query_params = {k: v for k, v in query_params.items() if v not in (None, "")}
        
        # Make the API request
        response = api_client.get(self.ENDPOINT, params=query_params)
        
        # Try to parse response data
        response_data = None
        try:
            response_data = response.json()
        except json.JSONDecodeError:
            # Some responses might not be JSON (e.g., XML, CSV formats)
            response_data = response.text
        
        # Validate the response
        self.validate_response(
            response.status_code,
            response_data,
            test_case.get("statusCode", 200),
            test_case.get("scenario", "unknown scenario"),
            schema_validator
        )
        
        # Additional validation for successful responses
        if response.status_code == 200:
            # Validate format-specific expectations
            requested_format = test_case.get("format")
            if requested_format == "json" and isinstance(response_data, list):
                # For JSON format, verify we got an array response
                assert isinstance(response_data, list), "Expected JSON array response"
            
            elif requested_format == "xml" and isinstance(response_data, str):
                # For XML format, verify we got a string containing XML
                assert response_data.strip().startswith("<?xml"), "Expected XML response"
            
            elif requested_format == "csv" and isinstance(response_data, str):
                # For CSV format, verify we got a string containing CSV data
                assert "," in response_data, "Expected CSV response with comma-separated values"


if __name__ == "__main__":
    pytest.main(["-v"])
