# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=100d61e03c
# 
# 

# ********RoostGPT********
Feature: /2.1/laureate/{laureateID} endpoint

Background:
  * url '{{ $processEnvironment.API_HOST }}/2.1'

  * configure headers = {Authorization: '{{$processEnvironment.AUTH_TOKEN}}'}
  
  * def laureateIDPayload = read('laureate_laureateID_get.csv')
    * payload laureateIDPayload
  
Scenario Outline: Test GET /laureate/{laureateID} with valid laureateID
  Given path '/laureate/<laureateID>'
  When method GET
  Then status 200
  And match header Content-Type contains 'application/json'
  And match response == read('laureate_laureateID_get_200_response.json')

  Examples:
  | laureateIDPayload |
  
Scenario Outline: Test GET /laureate/{laureateID} with invalid laureateID
  Given path '/laureate/<laureateID>'  
  When method GET
  Then status 400
  And match header Content-Type contains 'application/json'
  And match response.code == 'string'
  And match response.message == 'string'

  Examples:
  | laureateID |
  | 0          |
  | -1         |
  
Scenario: Test GET /laureate/{laureateID} with non-existent laureateID
  Given path '/laureate/999999'
  When method GET 
  Then status 404
  And match header Content-Type contains 'application/json'
  And match response.code == 'string'
  And match response.message == 'string'
  
Scenario Outline: Test GET /laureate/{laureateID} with invalid laureateID format
  Given path '/laureate/<laureateID>'
  When method GET
  Then status 422 
  And match header Content-Type contains 'application/json'
  And match response.code == 'string'
  And match response.message == 'string'
  
  Examples:
  | laureateID |
  | abc        |
  | 1.5        |
