# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Test Nobel Prize API

Background:
  * url target
  * def nobelPrizeCSV = read('classpath:nobelPrize_category_year_get.csv')

Scenario Outline: Get Nobel Prize by category and year - <category>, <year>

  Given path '/2.1/nobelPrize/<category>/<year>'
  And header Authorization = 'Bearer ' + karate.properties['token']
  When method GET
  Then status 200
  And match header Content-Type contains 'application/json'
  And match response.nobelPrize.awardYear == <year>
  And match response.nobelPrize.category.en == <categoryEN>
  And match response.nobelPrize.dateAwarded == '#? _ =~ /\\d{4}-\\d{2}-\\d{2}/'
  And match response.nobelPrize.prizeAmount == '#number'
  And match each response.nobelPrize.laureates == 
  """
    {
      id: '#number',
      name: {
        en: '#string',
        se: '##string',
        false: '##string'
      },
      portion: '#string',
      sortOrder: '#string',  
      motivation: {
        en: '#string',
        se: '##string',
        false: '##string'  
      },
      links: '##array'
    }
  """

  Examples:
    | category | year | categoryEN |
    | physics  | 1901 | Physics    |
    | chemistry| 1911 | Chemistry  |
    | peace    | 1921 | Peace      |

Scenario Outline: Get Nobel Prize for invalid category or year
  Given path '/2.1/nobelPrize/<invalidCategory>/<invalidYear>' 
  And header Authorization = 'Bearer ' + karate.properties['token']
  When method GET
  Then status 404
  And match header Content-Type contains 'application/json'
  And match response == 
  """
    {
      code: '404',
      message: 'There is not Laureate born that date'
    }
  """

  Examples:
    | invalidCategory | invalidYear |  
    | invalid         | 1901        |
    | peace           | 1800        |
    
Scenario: Get Nobel Prize with missing authorization
  Given path '/2.1/nobelPrize/peace/1901'
  When method GET
  Then status 401

