# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test api-testing-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=e702c0f931
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Laureate API

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:4010'
    * url urlBase
    * configure headers = { Authorization: '#(karate.properties['AUTH_TOKEN'])'}

  Scenario Outline: Get information about Nobel Prize Laureate through Laureate ID
    Given path '2.1', 'laureate', '<laureateID>'
    When method GET
    Then status 200
    And match responseHeaders['Content-Type'][0] == 'application/json;charset=utf-8'
    And match response.laureate.id == <laureateID>
    And match response.laureate.laureateIfPerson.knownName.en == '<knownName>'
    And match response.laureate.laureateIfPerson.givenName.en == '<givenName>'

    Examples:
      | read('laureate_laureateID_get.csv') |
