# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=e702c0f931
# 
# 

# ********RoostGPT********
Feature: Test the Laureate Endpoints of Nobel Prize Laureate API

  Background:
    * def urlBase = karate.properties['test_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: '#(karate.properties['test_AUTH_TOKEN'])' }

  Scenario Outline: Test GET Laureate Information
    Given path '/2.1/laureate', '<laureateID>'
    When method get
    Then status 200
    And match response.code == 200
    And match response.laureate.id == '<laureateID>'
    And match response.laureate.laureateIfPerson.fullName.en == '#string'
    And match response.laureate.laureateIfPerson.birth.place.city.en == '#string'
    And match response.laureate.laureateIfPerson.birth.date == '#string'
    And match response.laureate.laureateIfPerson.death.date == '#string'
    And def prizeYear = karate.convert(response.laureate.nobelPrizes.awardYear, 'int')
    And match prizeYear == '#number'

    Examples:
      | read('laureate_laureateID_get.csv') |
