# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureates_get for http method type GET 
# RoostTestHash=ff433d7857
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Laureates API

  Background:
    * def urlBase = karate.properties['test_URL_BASE'] || 'http://localhost:4010'
    * url urlBase

  Scenario Outline: GET Laureates API test with valid parameters
    Given path '/2.1/laureates'
    And params { offset: '<offset>', limit: '<limit>', sort: '<sort>', ID: '<ID>', name: '<name>', gender: '<gender>', motivation: '<motivation>', affiliation: '<affiliation>', residence: '<residence>', birthDate: '<birthDate>', birthDateTo: '<birthDateTo>', deathDate: '<deathDate>', deathDateTo: '<deathDateTo>' }
    When method get
    Then status 200
    And match response.meta.offset == '<offset>'
    And match response.meta.limit == '<limit>'
    And match response.meta.ID == '#number'
    And match response.meta.name contains '<name>'
    And match response.meta.gender == '<gender>'
    And match response.meta.affiliation contains '<affiliation>'
    And match response.meta.residence contains '<residence>'

    Examples:
      | read('laureates_get.csv') |

  Scenario: GET Laureates API Test for 'Not Found' error
    Given path '/2.1/laureates'
    And params { offset: 1, limit: 10, sort: 'asc', ID: 1234 }
    When method get
    Then status 404
    And match response.code contains '404'

  Scenario: GET Laureates API Test for 'Unprocessable Entity' error
    Given path '/2.1/laureates'
    And params { offset: 1, limit: 10, sort: 'asc', ID: 'abc' }
    When method get
    Then status 422
    And match response.message contains 'There is not Laureate born that date'
