# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureates_get for http method type GET 
# RoostTestHash=ff433d7857
# 
# 

# ********RoostGPT********
Feature: Test /2.1/laureates API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: '#(karate.properties['AUTH_TOKEN'])' }

  Scenario Outline: Test GET laureates API
    Given path '/2.1/laureates'
    And param offset = '<offset>'
    And param limit = '<limit>'
    And param sort = '<sort>'
    And param ID = '<ID>'
    When method get
    Then status 200
    And match response.meta.offset == <offset>
    And match response.meta.limit == <limit>
    And match response.meta.sort == '<sort>'
    And match response.meta.ID == '<ID>'
    * def res = response.laureates[0]
    And match each res.id contains '#number'
    And match each res.laureateIfPerson contains '__valid'
    And match each res.laureateIfOrg contains '__valid'

    Examples:
      | read('laureates_get.csv') |
