# ********RoostGPT********

# Test generated by RoostGPT for test k-api-dbrx-may23 using AI Type DBRX and AI Model meta-llama-3-70b-instruct-041824
# 
# Test generated by RoostGPT for test k-api-dbrx-may23 using AI Type DBRX and AI Model meta-llama-3-70b-instruct-041824
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=56bfcadf64
# 
# 

# ********RoostGPT********
Feature: Get Laureate by ID

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Get Laureate by ID
    Given path '2.1', 'laureate', <laureateID>
    When method get
    Then status <statusCode>
    And match responseHeaders['Content-Type'] == 'application/json'
    And match response ==
      """
      {
        "code": <code>,
        "message": <message>
      }
      """

    Examples:
      | read('laureate_laureateID_get.csv') |

  Scenario Outline: Get Laureate by ID with Invalid Input
    Given path '2.1', 'laureate', <laureateID>
    When method get
    Then status <statusCode>
    And match responseHeaders['Content-Type'] == 'application/json'
    And match response ==
      """
      {
        "code": <code>,
        "message": <message>
      }
      """

    Examples:
      | read('laureate_laureateID_get.csv') |
