# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Obtain information about one specific Nobel Prize

  Background:
    * def urlBase = karate.properties['test_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Fetch Nobel Prize details for a specific category and year
    Given path '2.1/nobelPrize', '<category>', '<year>'
    When method get
    Then status 200
    And match response == { nobelPrize: '#object' }
    And match response.nobelPrize ==
      """
      {
        awardYear: '#number',
        category: '#object',
        categoryFullName: '#object',
        dateAwarded: '#string',
        prizeAmount: '#number',
        prizeAmountAdjusted: '#number',
        topMotivation: '#object',
        laureates: '#array'
      } 
      """

    Examples:
      | read('nobelPrize_category_year_get.csv') |
