# ********RoostGPT********

# Test generated by RoostGPT for test k-api-dbrx-may23 using AI Type DBRX and AI Model meta-llama-3-70b-instruct-041824
# 
# Test generated by RoostGPT for test k-api-dbrx-may23 using AI Type DBRX and AI Model meta-llama-3-70b-instruct-041824
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: Testing Nobel Prize API Endpoint

  Scenario: Get Nobel Prize Information with default parameters
    Given url urlBase + '/2.1/nobelPrizes'
    When method GET
    Then status 200
    And match response ==
      """
      {
        "nobelPrizes": "#[]",
        "meta": "#object",
        "links": "#[]"
      }
      """

  Scenario: Get Nobel Prize Information with valid query parameters
    Given url urlBase + '/2.1/nobelPrizes?nobelPrizeYear=2010&limit=10&sort=asc'
    When method GET
    Then status 200
    And match response ==
      """
      {
        "nobelPrizes": "#[]",
        "meta": "#object",
        "links": "#[]"
      }
      """

  Scenario: Get Nobel Prize Information with invalid query parameters
    Given url urlBase + '/2.1/nobelPrizes?nobelPrizeYear=abc&limit=10&sort=asc'
    When method GET
    Then status 400
    And match response ==
      """
      {
        "code": "#string",
        "message": "#string"
      }
      """

  Scenario Outline: Get Nobel Prize Information with different query parameters
    Given url urlBase + '/2.1/nobelPrizes?nobelPrizeYear=<nobelPrizeYear>&limit=<limit>&sort=<sort>'
    When method GET
    Then status 200
    And match response ==
      """
      {
        "nobelPrizes": "#[]",
        "meta": "#object",
        "links": "#[]"
      }
      """

    Examples:
      | read('nobelPrizes_get.csv') |

  Scenario: Get Nobel Prize Information with authorization
    Given url urlBase + '/2.1/nobelPrizes'
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    When method GET
    Then status 200
    And match response ==
      """
      {
        "nobelPrizes": "#[]",
        "meta": "#object",
        "links": "#[]"
      }
      """
