# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test api-testing-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Details

Background:
  * def urlBase = karate.properties['url.base'] || 'http://localhost:4010'
  * url urlBase
  * def auth = karate.properties['AUTH_TOKEN'] ? { Authorization: karate.properties['AUTH_TOKEN'] } : {}

Scenario Outline: Retrieve details of specific Nobel Prize
  Given path '2.1/nobelPrize/', '<category>', '/', '<year>'
  And headers auth
  When method get
  Then match responseStatus == '<responseCode>'
  And match response.nobelPrize.awardYear == '#number'
  And match response.nobelPrize.category.en == '#string'
  And match response.nobelPrize.category.se == '#string'
  And match response.nobelPrize.category.de == '#string'
  And match response.nobelPrize.categoryFullName.en == '#string'
  And match response.nobelPrize.categoryFullName.se == '#string'
  And match response.nobelPrize.categoryFullName.de == '#string'
  And match response.nobelPrize.dateAwarded == '#string'
  And match response.nobelPrize.prizeAmount == '#number'
  And match response.nobelPrize.prizeAmountAdjusted == '#number'
  And match response.nobelPrize.topMotivation.en == '#string'
  And match response.nobelPrize.topMotivation.se == '#string'
  And match response.nobelPrize.topMotivation.de == '#string'
  And match each response.nobelPrize.laureates contains 
  { id:'#number', name: { en: '#string', se: '#string', de: '#string' }, 
  portion: '#string', sortOrder: '#string', 
  motivation: { en: '#string', se: '#string', de: '#string' }, links: '#array' }
  
  Examples:
    | category | year | responseCode |
    | 'phy'    | 2018 |          200 |
    | 'che'    | 2000 |          404 |
    | 'med'    | 1977 |          404 |
