# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Test generated by RoostGPT for test api-testing-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: nobelPrizes endpoint
  Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
  * url urlBase

  Scenario Outline: Verify the nobelPrizes endpoint
  Given path '/2.1/nobelPrizes'
  And params {
    "offset": '<offset>', "limit": '<limit>', 
    "sort": '<sort>', "nobelPrizeYear": <nobelPrizeYear>, 
    "yearTo": <yearTo>, "nobelPrizeCategory": '<nobelPrizeCategory>', 
    "format": '<format>', "csvLang": '<csvLang>'
    }
  When method GET
  Then status 200
  And match response == { 
    "nobelPrizes": '#array',
    "meta": '#object',
    "links": '#array'
    }

  And match response.meta == {
    "offset": '#int', "limit": '#int',
    "nobelPrizeYear": '#int', "yearTo": '#int',
    "nobelPrizeCategory": '#string', "count": '#int'
    }

  And match each response.nobelPrizes contains {
    "awardYear": '#int', "category": '#object', 
    "categoryFullName": '#object', "dateAwarded": '#string',
    "prizeAmount": '#int', "prizeAmountAdjusted": '#int',
    "topMotivation": '#object', "laureates": '#array'
    }

  Examples:
    | offset | limit | sort  | nobelPrizeYear | yearTo | nobelPrizeCategory | format | csvLang |
    | '2'    | '5'   | 'asc' |           1977 |   1985 | 'eco'              | 'json' | 'en'    |
