# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: Test Nobel Prize API

  Background:
    * configure headers = { 'Authorization': '#(karate.properties['test_AUTH_TOKEN'])' }
    * def urlBase = karate.properties['test_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test all possible response with valid parameters
    Given path '/2.1/nobelPrizes'
    And param 'offset' = <offset>
    And param 'limit' = <limit>
    And param 'sort' = '<sort>'
    And param 'nobelPrizeYear' = <nobelPrizeYear>
    And param 'yearTo' = <yearTo>
    And param 'nobelPrizeCategory' = '<nobelPrizeCategory>'
    When method get
    Then status 200
    And match $.nobelPrizes contains {'awardYear':'#number', 'dateAwarded':'#string', 'prizeAmount':'#number', 'prizeAmountAdjusted':'#number'}
    And match $.meta contains {'offset':'#number', 'limit':'#number', 'nobelPrizeYear':'#number', 'yearTo':'#number', 'nobelPrizeCategory':'#string'}

    Examples:
      | read('nobelPrizes_get.csv') |

  Scenario Outline: Test all possible response with invalid parameters
    Given path '/2.1/nobelPrizes'
    And param 'offset' = <offset>
    And param 'limit' = <limit>
    And param 'sort' = '<sort>'
    And param 'nobelPrizeYear' = <nobelPrizeYear>
    And param 'yearTo' = <yearTo>
    And param 'nobelPrizeCategory' = '<nobelPrizeCategory>'
    When method get
    Then status 422
    And match $ contains {'code':'#string', 'message':'#string'}

    Examples:
      | offset | limit | sort  | nobelPrizeYear | yearTo | nobelPrizeCategory |
      |     -1 |     0 | 'xyz' |           1800 |   1899 | 'xyz'              |

  Scenario: Test with no parameters
    Given path '/2.1/nobelPrizes'
    When method get
    Then status 200
